(()=>{
const q=id=>document.getElementById(id);
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function style(){let s=q('acompExportStyle');if(!s){s=document.createElement('style');s.id='acompExportStyle';document.head.appendChild(s)}s.textContent=`#acomp .box{padding:20px;background:#f5f7f9}#acomp h2{margin:0 0 4px}.acompToolbar{display:flex;gap:9px;flex-wrap:wrap;align-items:center;margin:12px 0 16px}.acompBtn{border:0;border-radius:9px;padding:10px 14px;font-weight:800;cursor:pointer}.acompBtn.pdf{background:#df1017;color:#fff}.acompBtn.img{background:#20252b;color:#fff}#acompExportArea{background:#fff;padding:10px;border:1px solid #d8dee5;border-radius:12px;overflow:auto}#acompExportArea table{border-collapse:separate!important;border-spacing:0!important;min-width:1450px!important;background:#fff;border:1px solid #cfd6dd;border-radius:8px;overflow:hidden}#acompExportArea th{position:static!important;background:#e9edf1!important;color:#17202a!important;font-size:11px!important;font-weight:900!important;line-height:1.15!important;text-align:center!important;vertical-align:middle!important;padding:11px 8px!important;border-right:1px solid #c8d0d8!important;border-bottom:2px solid #aeb8c2!important;min-width:118px;max-width:145px;white-space:normal}#acompExportArea th:first-child{min-width:190px;text-align:left!important}#acompExportArea td{padding:0!important;border-right:1px solid #d5dbe1!important;border-bottom:1px solid #d5dbe1!important;vertical-align:middle!important;background:#fff}#acompExportArea tbody tr:nth-child(even) td{background:#fafbfc}#acompExportArea .namecell{font-size:14px;font-weight:900;padding:12px!important;white-space:nowrap;background:#f2f4f6!important;border-right:2px solid #b9c2cb!important}.acompCell{min-width:118px!important;text-align:center!important}.acompCard{margin:5px;padding:7px 5px;border-radius:7px;background:#fff;border:1px solid #e0e4e8;line-height:1.15}.acompMeta{color:#111;font-size:11px;font-weight:700;margin-bottom:3px}.acompMeta strong{font-size:16px}.acompReal{font-size:11px;font-weight:700;margin-bottom:4px}.acompReal strong{font-size:18px}.acompReal.ok{color:#16803a!important}.acompReal.bad{color:#cf2028!important}.acompFalta{padding-top:4px;border-top:1px solid #e3e6e9;font-size:10px;color:#59636d;font-weight:700}.acompFalta.ok{color:#16803a!important}.acompCard.hit{border-left:4px solid #16803a;background:#f1faf4}.acompCard.miss{border-left:4px solid #cf2028;background:#fff5f5}@media(max-width:700px){#acomp .box{padding:10px}#acompExportArea{padding:4px}.acompToolbar .small{width:100%}}`;}
function render(){if(!window.dash||!q('thAcomp')||!q('tbAcomp'))return;const cats=window.dash.categorias||[];q('thAcomp').innerHTML='<tr><th>CONSULTOR</th>'+cats.map(c=>`<th>${esc(c.nome)}</th>`).join('')+'</tr>';q('tbAcomp').innerHTML=(window.dash.individual||[]).map(i=>'<tr><td class="namecell">'+esc(i.rota+' - '+i.nome)+'</td>'+(i.resultados||[]).map(r=>{const meta=Number(r.meta||0),real=Number(r.realizado||0),falta=Math.max(meta-real,0),ok=real>=meta;return `<td class="acompCell"><div class="acompCard ${ok?'hit':'miss'}"><div class="acompMeta">META<br><strong>${meta}</strong></div><div class="acompReal ${ok?'ok':'bad'}">REALIZADO<br><strong>${real}</strong></div><div class="acompFalta ${ok?'ok':''}">${ok?'✓ META ATINGIDA':'FALTA '+falta}</div></div></td>`}).join('')+'</tr>').join('')}
function toolbar(){const sec=q('acomp');if(!sec)return;const box=sec.querySelector('.box');if(!box)return;let bar=q('acompToolbar');if(!bar){bar=document.createElement('div');bar.id='acompToolbar';bar.className='acompToolbar';bar.innerHTML='<button class="acompBtn img" onclick="exportarAcompImagem()">🖼️ BAIXAR IMAGEM</button><button class="acompBtn pdf" onclick="exportarAcompPDF()">📄 BAIXAR PDF</button><span class="small">Tabela completa em alta resolução.</span>';box.querySelector('p')?.insertAdjacentElement('afterend',bar)}const table=box.querySelector('table');if(table&&!q('acompExportArea')){const w=document.createElement('div');w.id='acompExportArea';table.parentNode.insertBefore(w,table);w.appendChild(table)}}
function load(src,test){return new Promise((ok,no)=>{if(test())return ok();const s=document.createElement('script');s.src=src;s.onload=ok;s.onerror=()=>no(Error('Não foi possível carregar o recurso de exportação.'));document.head.appendChild(s)})}
async function capture(){await load('https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js',()=>!!window.html2canvas);const a=q('acompExportArea');if(!a)throw Error('Tabela não encontrada.');const old={w:a.style.width,o:a.style.overflow};a.style.width=Math.max(a.scrollWidth,1450)+'px';a.style.overflow='visible';try{return await html2canvas(a,{scale:3,backgroundColor:'#fff',useCORS:true,logging:false,windowWidth:a.scrollWidth+100})}finally{a.style.width=old.w;a.style.overflow=old.o}}
window.exportarAcompImagem=async()=>{try{const c=await capture(),a=document.createElement('a');a.download='acompanhamento-geral-iturama.png';a.href=c.toDataURL('image/png',1);a.click()}catch(e){alert(e.message)}};
window.exportarAcompPDF=async()=>{try{const c=await capture();await load('https://cdn.jsdelivr.net/npm/jspdf@2.5.1/dist/jspdf.umd.min.js',()=>!!window.jspdf?.jsPDF);const {jsPDF}=jspdf,p=new jsPDF({orientation:'landscape',unit:'mm',format:'a3'}),pw=p.internal.pageSize.getWidth(),ph=p.internal.pageSize.getHeight(),m=7,w=pw-2*m,h=c.height*w/c.width,img=c.toDataURL('image/jpeg',.97);if(h<=ph-2*m)p.addImage(img,'JPEG',m,m,w,h);else{const pageH=ph-2*m,srcH=c.height*(pageH/h);let y=0,n=0;while(y<c.height){if(n++)p.addPage('a3','landscape');const x=document.createElement('canvas');x.width=c.width;x.height=Math.min(srcH,c.height-y);x.getContext('2d').drawImage(c,0,y,c.width,x.height,0,0,c.width,x.height);p.addImage(x.toDataURL('image/jpeg',.97),'JPEG',m,m,w,x.height*w/c.width);y+=srcH}}p.save('acompanhamento-geral-iturama.pdf')}catch(e){alert(e.message)}};
function install(){style();toolbar();if(typeof window.renderAcomp==='function'&&!window.renderAcomp.__visual2){const old=window.renderAcomp;window.renderAcomp=function(){old();render();toolbar()};window.renderAcomp.__visual2=true}render();toolbar()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,250));else setTimeout(install,250);setTimeout(install,1200);setTimeout(render,2500);
})();