(()=>{
const API='https://harlrfhukjvhpufwhtep.supabase.co/functions/v1/admin-access-api';
const $=id=>document.getElementById(id),E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let items=[];
async function postAccess(action,body={}){const token=sessionStorage.getItem('admToken')||'';const r=await fetch(API,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,token,...body})});const j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw Error(j.error||'Erro de conexão');return j}
function css(){if($('acompAccessStyle'))return;const s=document.createElement('style');s.id='acompAccessStyle';s.textContent=`.acompAccessBox{border:2px solid #e30613;border-radius:16px;padding:15px;margin:0 0 18px;background:#fff8f8}.acompAccessHead{display:flex;justify-content:space-between;gap:10px;align-items:flex-start;flex-wrap:wrap}.acompAccessHead h3{margin:0 0 5px}.acompAccessForm{display:grid;grid-template-columns:1fr 1fr 1fr;gap:9px;margin-top:12px}.acompAccessList{margin-top:13px;display:grid;gap:8px}.acompAccessItem{border:1px solid #dce2e7;border-radius:12px;padding:10px;background:#fff;display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center}.acompAccessBadge{display:inline-block;padding:4px 8px;border-radius:999px;font-size:11px;font-weight:900;background:#eaf4fb}.acompAccessBadge.off{background:#eee;color:#777}@media(max-width:760px){.acompAccessForm{grid-template-columns:1fr}.acompAccessItem{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function ensure(){css();const list=$('listaConsultores'),box=list?.closest('.box');if(!list||!box)return false;if($('acompAccessBox'))return true;const d=document.createElement('div');d.id='acompAccessBox';d.className='acompAccessBox';d.innerHTML=`<div class="acompAccessHead"><div><h3>👁 Acesso de Acompanhamento</h3><div class="small">Crie matrícula e senha para uma pessoa acompanhar todos os consultores. Esse perfil é somente de consulta e não altera metas, vendas ou cadastros.</div></div><span class="acompAccessBadge">TODOS OS CONSULTORES</span></div><input id="acompId" type="hidden"><div class="acompAccessForm"><div><label>Nome da pessoa</label><input id="acompNome" placeholder="Ex.: Coordenador"></div><div><label>Matrícula</label><input id="acompMat" autocomplete="off" placeholder="Matrícula de acesso"></div><div><label>Senha</label><input id="acompSenha" type="password" autocomplete="new-password" placeholder="Mínimo 4 caracteres"></div></div><label style="display:flex;align-items:center;gap:8px;margin-top:10px;font-weight:800"><input id="acompAtivo" type="checkbox" checked style="width:auto"> Acesso ativo</label><div class="action" style="margin-top:10px"><button id="acompSalvar" class="red">SALVAR ACESSO</button><button id="acompNovo">NOVO</button></div><div id="acompStatus" class="small" style="margin-top:8px"></div><div id="acompLista" class="acompAccessList"></div>`;box.insertBefore(d,list);$('acompSalvar').onclick=save;$('acompNovo').onclick=clear;load();return true}
function clear(){$('acompId').value='';$('acompNome').value='';$('acompMat').value='';$('acompSenha').value='';$('acompAtivo').checked=true;$('acompStatus').textContent=''}
function render(){const host=$('acompLista');if(!host)return;host.innerHTML=items.length?items.map(x=>`<div class="acompAccessItem"><div><b>${E(x.nome)}</b><div class="small">Matrícula: <b>${E(x.matricula)}</b> • <span class="acompAccessBadge ${x.ativo?'':'off'}">${x.ativo?'ATIVO':'INATIVO'}</span></div></div><div class="action"><button data-edit="${x.id}">EDITAR</button><button data-del="${x.id}" style="background:#fff0f0;color:#b40000">EXCLUIR</button></div></div>`).join(''):'<div class="small">Nenhum acesso de acompanhamento criado ainda.</div>';host.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(Number(b.dataset.edit)));host.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>del(Number(b.dataset.del)))}
async function load(){if(!$('acompLista'))return;try{const j=await postAccess('list_observers');items=j.items||[];render()}catch(e){$('acompStatus').textContent=e.message}}
function edit(id){const x=items.find(i=>Number(i.id)===id);if(!x)return;$('acompId').value=String(x.id);$('acompNome').value=x.nome||'';$('acompMat').value=x.matricula||'';$('acompSenha').value='';$('acompSenha').placeholder='Deixe em branco para manter a senha';$('acompAtivo').checked=x.ativo!==false;$('acompStatus').textContent='Editando acesso de '+(x.nome||'')}
async function save(){const st=$('acompStatus');st.className='small';st.textContent='Salvando...';try{const id=$('acompId').value?Number($('acompId').value):null;await postAccess('save_observer',{id,nome:$('acompNome').value.trim(),matricula:$('acompMat').value.trim(),senha:$('acompSenha').value,ativo:$('acompAtivo').checked});st.className='ok';st.textContent='Acesso salvo com sucesso.';clear();await load()}catch(e){st.className='bad';st.textContent=e.message}}
async function del(id){const x=items.find(i=>Number(i.id)===id);if(!x||!confirm('Excluir o acesso de '+x.nome+'?'))return;try{await postAccess('delete_observer',{id});await load()}catch(e){$('acompStatus').className='bad';$('acompStatus').textContent=e.message}}
function boot(){if(!ensure())setTimeout(boot,200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();setInterval(()=>{if(document.getElementById('app')&&!document.getElementById('app').classList.contains('hide'))ensure()},1500);
})();