(()=>{
const PLUS='https://harlrfhukjvhpufwhtep.supabase.co/functions/v1/admin-api-plus';
const CFG='https://harlrfhukjvhpufwhtep.supabase.co/functions/v1/admin-config-api';
const q=id=>document.getElementById(id),E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function installPost(){if(typeof post!=='function'){setTimeout(installPost,150);return}if(post.__b2b)return;const f=async x=>{const r=await fetch(PLUS,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(x)}),j=await r.json();if(!r.ok)throw Error(j.error||'Erro');return j};f.__b2b=true;post=f}
async function cfg(body){const r=await fetch(CFG,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)throw Error(j.error||'Erro');return j}
function renderB2BBuilder(){const b=q('cmBuilder');if(!b)return;b.innerHTML='<b>Compra / Recompra B2B</b><p class="small">Regra automática pela coluna Origem e pela Data da Nota Fiscal.</p><div class="notice"><b>COMPRA:</b> cliente com Origem = B2B em pelo menos 1 data.<br><b>RECOMPRA:</b> cliente com Origem = B2B em 2 ou mais datas diferentes.<br>Várias linhas na mesma data contam como uma única compra.</div>';const p=q('cmPreview');if(p)p.innerHTML='<b>Como será buscado nas vendas:</b><div>Origem = B2B • datas diferentes definem Compra ou Recompra.</div>'}
function installCategory(){const mode=q('cmMode');if(!mode){setTimeout(installCategory,200);return}if(mode.querySelector('option[value="b2b"]'))return;mode.insertAdjacentHTML('beforeend','<option value="b2b">Compra / Recompra B2B</option>');
const oldMode=window.cmModeChanged;window.cmModeChanged=function(){if(mode.value==='b2b'){const qty=q('cmUseQty');if(qty){qty.checked=false;q('cmQtyFields')&&(q('cmQtyFields').style.display='none')}renderB2BBuilder();return}oldMode?.()};
const oldEdit=window.cmEditCategory;window.cmEditCategory=async function(id){await oldEdit(id);const c=(config?.categorias||[]).find(x=>Number(x.id)===Number(id));if(String(c?.tipo_regra||'')==='b2b'){mode.value='b2b';renderB2BBuilder()}};
const oldSave=window.cmSaveCategory;window.cmSaveCategory=async function(){if(mode.value!=='b2b')return oldSave();const id=+q('cmId').value||null,nome=q('cmName').value.trim();if(!nome){q('cmStatus').className='bad';q('cmStatus').textContent='Informe o nome da categoria.';return}q('cmStatus').textContent='Salvando...';try{const r=await cfg({action:'save_category_full',token,id,nome,tipo_regra:'b2b',quantidade_minima:1,regras:[]});q('cmStatus').className='ok';q('cmStatus').textContent='Categoria B2B salva.';await carregarTudo();await window.cmEditCategory(r.id)}catch(e){q('cmStatus').className='bad';q('cmStatus').textContent=e.message}}}
function installViews(){if(typeof linha!=='function'||typeof renderVisaoResumo!=='function'){setTimeout(installViews,200);return}if(linha.__b2b)return;const oldLinha=linha;linha=function(r){if(String(r?.nome||'').toUpperCase()==='OPORTUNIDADE B2B')return `<tr><td><b>${E(r.nome)}</b><div class="small">Compra: ${r.compra||0} • Recompra: ${r.recompra||0}</div></td><td>${r.meta}</td><td>${r.realizado}</td><td class="${r.falta?'bad':'ok'}">${r.falta}</td><td>${r.percentual}%</td></tr>`;return oldLinha(r)};linha.__b2b=true;
const oldClientes=window.carregarClientesIncentivo;window.carregarClientesIncentivo=async function(){const idx=q('selIncentivo')?.value,rota=q('selVisao')?.value;if(idx==='')return oldClientes();try{if(!visaoDetalhe||visaoDetalhe.consultor?.rota!==rota)visaoDetalhe=await post({action:'consultor_view',token,rota});const r=visaoDetalhe.resultados[+idx];if(String(r?.nome||'').toUpperCase()!=='OPORTUNIDADE B2B')return oldClientes();const re=(r.clientes||[]).filter(c=>c.status==='RECOMPRA'),co=(r.clientes||[]).filter(c=>c.status!=='RECOMPRA');const rows=a=>a.length?a.map(c=>`<tr><td>${E(c.cliente)}</td><td>${E(c.razao)}</td><td>${E((c.datas||[]).map(d=>String(d).split('-').reverse().join('/')).join(' • '))}</td></tr>`).join(''):'<tr><td colspan="3">Nenhum cliente.</td></tr>';q('clientesVisao').innerHTML=`<div class="cards" style="margin-top:14px"><div class="mini"><span>Compra</span><strong>${r.compra||0}</strong></div><div class="mini"><span>Recompra</span><strong>${r.recompra||0}</strong></div></div><h3>Recompra</h3><table><thead><tr><th>PV</th><th>Cliente</th><th>Datas B2B</th></tr></thead><tbody>${rows(re)}</tbody></table><h3>Compra</h3><table><thead><tr><th>PV</th><th>Cliente</th><th>Data B2B</th></tr></thead><tbody>${rows(co)}</tbody></table>`}catch(e){q('clientesVisao').innerHTML='<p class="bad">'+E(e.message)+'</p>'}}
}
function boot(){installPost();setTimeout(()=>{installCategory();installViews()},250)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();