(()=>{
const CFGAPI='https://harlrfhukjvhpufwhtep.supabase.co/functions/v1/admin-config-api';
let cmGroups=[[]],cmRules=[],cmOptionsCache={};
const q=id=>document.getElementById(id);
const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fieldLabel=f=>({material:'Código / Material',marca:'Marca',descricao:'Descrição',origem:'Origem'}[f]||f);
async function cfgPost(x){const r=await fetch(CFGAPI,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(x)}),j=await r.json();if(!r.ok)throw Error(j.error||'Erro');return j}
function install(){
  const btn=[...document.querySelectorAll('.tabs button')].find(b=>String(b.getAttribute('onclick')||'').includes("aba('metas'"));
  if(btn)btn.textContent='🎯 Metas e Categorias';
  const sec=q('metas');if(!sec)return;
  sec.innerHTML=`<div class="box"><h2>Metas e Categorias</h2><div class="notice"><b>Defina como a categoria será encontrada na planilha de vendas.</b> Escolha a coluna da planilha e selecione os valores que já existem na base de Vendas.</div><div class="form2"><div><h3>Categorias</h3><button class="red" onclick="cmNewCategory()">+ NOVA CATEGORIA</button><div id="cmCatList" style="margin-top:12px"></div></div><div><h3>Editar categoria</h3><input id="cmId" type="hidden"><div class="form2"><div><label>Nome da categoria</label><input id="cmName" placeholder="Ex.: COBERTURA HEINEKEN"></div><div><label>Buscar na coluna da planilha</label><select id="cmField" onchange="cmFieldChanged()"><option value="material">Código / Material</option><option value="marca">Marca</option><option value="descricao">Descrição</option><option value="origem">Origem</option></select></div></div><div style="margin-top:10px"><label>Regra</label><select id="cmMode" onchange="cmModeChanged()"><option value="ou">Qualquer um (OU)</option><option value="todos">Todos obrigatórios (E)</option><option value="grupos">Grupos obrigatórios</option></select></div><div id="cmBuilder" style="border:1px solid #e1e5e9;border-radius:14px;padding:14px;margin-top:12px;background:#fafbfc"></div><div style="margin-top:10px"><label>Tabela no Acompanhamento (ADM)</label><select id="cmPriority"><option value="1">Prioridade (Tabela 1)</option><option value="2">Prioridade 2 (Tabela 2)</option></select><p class="small">Altera somente o Acompanhamento do administrador.</p></div><div style="margin-top:10px"><label>Posição na tabela</label><input id="cmPosition" type="number" min="1" max="9999" value="999"></div><div class="action" style="margin-top:10px"><button type="button" onclick="cmSavePlacement()" style="background:#1769aa;color:#fff">SALVAR SOMENTE TABELA E POSIÇÃO</button></div><div style="margin-top:10px"><label>Excluir subcanal (opcional)</label><input id="cmExclude" placeholder="Ex.: DEPOSITO DE BEBIDAS"></div><div class="action" style="margin-top:12px"><button class="red" onclick="cmSaveCategory()">SALVAR CATEGORIA E REGRA</button><button onclick="cmNewCategory()">NOVA / LIMPAR</button><button id="cmDelete" class="dark" onclick="cmDeleteCategory()">EXCLUIR CATEGORIA</button></div><p id="cmStatus"></p><div id="cmPreview" class="notice" style="background:#f7f8fa"></div></div></div></div><div class="box"><h2>Alterar Meta</h2><div class="form3"><div><label>Consultor</label><select id="metaRota" onchange="carregaMetaAtual()"></select></div><div><label>Categoria</label><select id="metaCat" onchange="carregaMetaAtual()"></select></div><div><label>Nova meta</label><input id="metaValor" type="number" min="0"></div></div><button class="red" onclick="salvarMeta()">SALVAR META</button><p id="metaStatus"></p></div>`;
  const old=renderBase;renderBase=function(){old();cmRenderCategoryList()};
  if(config){const opts=dash.consultores.map(c=>`<option value="${E(c.rota)}">${E(c.rota)} - ${E(c.nome)}</option>`).join('');q('metaRota').innerHTML=opts;q('metaCat').innerHTML=dash.categorias.map(c=>`<option value="${c.id}">${E(c.nome)}</option>`).join('');cmRenderCategoryList();carregaMetaAtual()}
  cmNewCategory();
}
function cmRenderCategoryList(){if(!config||!q('cmCatList'))return;
 const cats=[...(config.categorias||[])].sort((a,b)=>Number(a.posicao_acomp??a.ordem??999)-Number(b.posicao_acomp??b.ordem??999)||Number(a.id)-Number(b.id));
 const group=(priority,title)=>{const items=cats.filter(c=>Number(c.prioridade_acomp||2)===priority);return `<section style="border:1px solid #dce5ef;border-radius:14px;padding:10px;margin:12px 0;background:#fff"><h3 style="margin:0 0 10px;padding:10px;border-radius:9px;background:${priority===1?'#dceefa':'#fff0d7'};color:#1e3446">${title} <small style="font-weight:normal">(${items.length})</small></h3>${items.map((c,i)=>`<div class="cmQuickRow" style="display:flex;align-items:center;gap:5px;margin-bottom:7px;background:#f6f7f8;border-radius:12px;padding:5px;min-width:0"><button id="cmCat_${c.id}" style="flex:1;min-width:0;text-align:left;background:transparent;color:#161b20;font-size:13px;overflow-wrap:anywhere;padding:9px 4px" onclick="cmEditCategory(${c.id})">${E(c.nome)}${c.tipo_regra==='recompra'?' • 🔁 Recompra':''}</button><button type="button" title="Enviar para ${priority===1?'Prioridade 2':'Prioridade'}" aria-label="Mover ${E(c.nome)} para ${priority===1?'Prioridade 2':'Prioridade'}" style="padding:8px 6px;background:#e8edf5;color:#17496d;font-size:11px;white-space:nowrap" onclick="cmQuickTable(${c.id},'${priority===1?2:1}')">→ T${priority===1?2:1}</button><div style="display:flex;flex-direction:column;gap:3px"><button type="button" title="Subir" aria-label="Subir ${E(c.nome)}" ${i===0?'disabled':''} style="padding:4px 9px;background:#dce9f5;color:#16446c" onclick="cmQuickMove(${c.id},-1)">↑</button><button type="button" title="Descer" aria-label="Descer ${E(c.nome)}" ${i===items.length-1?'disabled':''} style="padding:4px 9px;background:#dce9f5;color:#16446c" onclick="cmQuickMove(${c.id},1)">↓</button></div></div>`).join('')||'<p class="small">Nenhuma categoria nesta tabela.</p>'}</section>`};
 q('cmCatList').innerHTML=group(1,'PRIORIDADE — TABELA 1')+group(2,'PRIORIDADE 2 — TABELA 2');
}
let cmQuickBusy=false;
window.cmQuickTable=async function(id,value,sel){if(cmQuickBusy)return;const c=config.categorias.find(x=>Number(x.id)===Number(id));if(!c)return;cmQuickBusy=true;if(sel)sel.disabled=true;try{await cfgPost({action:'set_category_placement',token,id,prioridade_acomp:Number(value),posicao_acomp:9999});c.prioridade_acomp=Number(value);c.posicao_acomp=9999;if(Number(q('cmId')?.value)===Number(id)){q('cmPriority').value=String(value);q('cmPosition').value='9999'}cmRenderCategoryList();q('cmStatus').className='ok';q('cmStatus').textContent='Tabela alterada. Regras e metas preservadas.'}catch(e){if(sel)sel.value=String(c.prioridade_acomp||2);q('cmStatus').className='bad';q('cmStatus').textContent=e.message}finally{cmQuickBusy=false;if(sel)sel.disabled=false}};
window.cmQuickMove=async function(id,direction){if(cmQuickBusy)return;const c=config.categorias.find(x=>Number(x.id)===Number(id));if(!c)return;cmQuickBusy=true;try{await cfgPost({action:'reorder_category_placement',token,id,prioridade_acomp:Number(c.prioridade_acomp||2),direction});const list=config.categorias.filter(x=>Number(x.prioridade_acomp||2)===Number(c.prioridade_acomp||2)).sort((a,b)=>Number(a.posicao_acomp??a.ordem??999)-Number(b.posicao_acomp??b.ordem??999)||Number(a.id)-Number(b.id));const ix=list.findIndex(x=>Number(x.id)===Number(id)),to=ix+direction;if(to>=0&&to<list.length){[list[ix],list[to]]=[list[to],list[ix]];list.forEach((x,i)=>x.posicao_acomp=i+1)}cmRenderCategoryList();q('cmStatus').className='ok';q('cmStatus').textContent='Posição atualizada no acompanhamento.'}catch(e){q('cmStatus').className='bad';q('cmStatus').textContent=e.message}finally{cmQuickBusy=false}};
window.cmNewCategory=function(){q('cmId').value='';q('cmName').value='';q('cmField').value='material';q('cmMode').value='ou';q('cmExclude').value='';q('cmPriority').value='2';q('cmPosition').value='999';cmGroups=[[]];cmRules=[];q('cmDelete').style.display='none';document.querySelectorAll('[id^=cmCat_]').forEach(x=>x.style.background='#f6f7f8');q('cmStatus').textContent='';cmRenderBuilder()};
window.cmEditCategory=async function(id){const c=config.categorias.find(x=>Number(x.id)===Number(id));if(!c)return;document.querySelectorAll('[id^=cmCat_]').forEach(x=>x.style.background='#f6f7f8');const b=q('cmCat_'+id);if(b)b.style.background='#ffe5e5';q('cmId').value=id;q('cmName').value=c.nome;q('cmPriority').value=String(c.prioridade_acomp||2);q('cmPosition').value=String(c.posicao_acomp||c.ordem||999);q('cmDelete').style.display='inline-block';q('cmStatus').textContent='Carregando regra...';try{const r=await cfgPost({action:'category_rules',token,id});cmRules=r.regras||[];const campo=String(cmRules[0]?.campo||'material');q('cmField').value=['material','marca','descricao','origem'].includes(campo)?campo:'material';const gs=[...new Set(cmRules.map(x=>Number(x.grupo||0)))];if(String(c.tipo_regra||'').toLowerCase()==='grupos'){if(cmRules.length===gs.length&&cmRules.every(x=>(x.valores||[]).length===1))q('cmMode').value='todos';else q('cmMode').value='grupos'}else q('cmMode').value='ou';cmGroups=gs.length?gs.map(g=>cmRules.filter(x=>Number(x.grupo||0)===g).flatMap(x=>x.valores||[]).map(String)):[[]];q('cmExclude').value=[...new Set(cmRules.flatMap(x=>x.excluir_subcanais||[]))].join(', ');q('cmStatus').textContent='';cmRenderBuilder()}catch(e){q('cmStatus').className='bad';q('cmStatus').textContent=e.message}};
window.cmFieldChanged=function(){cmGroups=[[]];q('cmStatus').className='';q('cmStatus').textContent='Coluna alterada. Selecione os valores da planilha para esta origem.';cmRenderBuilder()};
window.cmModeChanged=function(){const m=q('cmMode').value;if(m!=='grupos')cmGroups=[cmGroups.flat().filter(Boolean)];if(!cmGroups.length)cmGroups=[[]];cmRenderBuilder()};
window.cmAddValue=function(g){const id=q('cmMode').value==='grupos'?'cmVal_'+g:'cmVal',el=q(id),v=String(el?.value||'').trim();if(!v)return;if(!cmGroups[g])cmGroups[g]=[];cmGroups[g]=cmGroups[g].filter(Boolean);if(!cmGroups[g].includes(v))cmGroups[g].push(v);cmRenderBuilder()};
window.cmAddPicked=function(g){const el=q('cmPick_'+g),v=String(el?.value||'').trim();if(!v)return;if(!cmGroups[g])cmGroups[g]=[];cmGroups[g]=cmGroups[g].filter(Boolean);if(!cmGroups[g].includes(v))cmGroups[g].push(v);cmRenderBuilder()};
window.cmDelValue=function(g,i){cmGroups[g]=cmGroups[g].filter(Boolean);cmGroups[g].splice(i,1);cmRenderBuilder()};
window.cmAddGroup=function(){cmGroups.push([]);cmRenderBuilder()};
window.cmDelGroup=function(i){if(cmGroups.length<=1)return;cmGroups.splice(i,1);cmRenderBuilder()};
function chips(g,gi){return `<div style="display:flex;flex-wrap:wrap;gap:7px;margin-top:8px">${g.filter(Boolean).map((v,i)=>`<span style="background:#eef2f4;border-radius:999px;padding:7px 10px;font-weight:700">${E(v)} <button style="padding:0 3px;background:transparent;color:#b00" onclick="cmDelValue(${gi},${i})">×</button></span>`).join('')}</div>`}
function picker(gi,label){return `<div style="margin:10px 0;padding:10px;border:1px solid #e1e5e9;border-radius:10px;background:#fff"><label>Selecionar ${E(label)} existente na planilha de Vendas</label><div class="form2" style="margin-top:6px"><select id="cmPick_${gi}"><option value="">Carregando opções...</option></select><button onclick="cmAddPicked(${gi})">+ ADICIONAR SELECIONADO</button></div><div id="cmOptStatus_${gi}" class="small" style="margin-top:5px"></div></div>`}
function fillPickers(field){const vals=cmOptionsCache[field];if(!vals)return;document.querySelectorAll('[id^=cmPick_]').forEach(sel=>{sel.innerHTML='<option value="">Selecione...</option>'+vals.map(v=>`<option value="${E(v)}">${E(v)}</option>`).join('')});document.querySelectorAll('[id^=cmOptStatus_]').forEach(el=>el.textContent=`${vals.length} opção(ões) encontrada(s) na planilha atual.`)}
async function cmLoadOptions(field){if(cmOptionsCache[field]){fillPickers(field);return}if(typeof token==='undefined'||!token){document.querySelectorAll('[id^=cmOptStatus_]').forEach(el=>el.textContent='As opções serão carregadas após entrar no ADM.');return}document.querySelectorAll('[id^=cmOptStatus_]').forEach(el=>el.textContent='Carregando opções da planilha...');try{const r=await cfgPost({action:'sales_options',token,campo:field});cmOptionsCache[field]=r.valores||[];fillPickers(field)}catch(e){document.querySelectorAll('[id^=cmOptStatus_]').forEach(el=>el.textContent='Não foi possível carregar as opções: '+e.message)}}
function cmRenderBuilder(){if(!q('cmBuilder'))return;const m=q('cmMode').value,f=q('cmField').value,label=fieldLabel(f);if(m==='ou'||m==='todos'){const vals=cmGroups.flat().filter(Boolean);cmGroups=[vals];q('cmBuilder').innerHTML=`<b>${m==='ou'?'Qualquer um (OU)':'Todos obrigatórios (E)'}</b><p class="small">${m==='ou'?`Se vender qualquer valor de ${E(label)}, conta 1 cobertura por cliente.`:`O cliente precisa atender todos os valores de ${E(label)} cadastrados.`}</p>${picker(0,label)}<div class="form2"><input id="cmVal" placeholder="Ou digite ${E(label)} manualmente"><button onclick="cmAddValue(0)">+ ADICIONAR</button></div>${chips(cmGroups[0],0)}`}else{q('cmBuilder').innerHTML=`<b>Grupos obrigatórios</b><p class="small">Dentro do grupo vale OU; todos os grupos precisam ser atendidos.</p>${cmGroups.map((g,gi)=>`<div style="border:1px solid #dfe4e8;border-radius:12px;padding:12px;margin:10px 0;background:#fff"><div class="action"><b>Grupo ${gi+1}</b><button onclick="cmDelGroup(${gi})">Excluir grupo</button></div>${picker(gi,label)}<div class="form2"><input id="cmVal_${gi}" placeholder="Ou digite ${E(label)} manualmente"><button onclick="cmAddValue(${gi})">+ ADICIONAR</button></div>${chips(g,gi)}</div>`).join('')}<button onclick="cmAddGroup()">+ ADICIONAR GRUPO</button>`}cmPreview();cmLoadOptions(f)}
function cmPreview(){const m=q('cmMode').value,f=q('cmField').value;let t='';if(m==='ou')t=(cmGroups[0]||[]).filter(Boolean).join(' OU ');if(m==='todos')t=(cmGroups[0]||[]).filter(Boolean).join(' E ');if(m==='grupos')t=cmGroups.map(g=>'('+(g.filter(Boolean).join(' OU '))+')').join(' E ');q('cmPreview').innerHTML=`<b>Como será buscado nas vendas:</b><div>${E(fieldLabel(f))}: ${E(t||'selecione os valores da planilha acima')}</div>`}
window.cmSavePlacement=async function(){const id=Number(q('cmId').value),priority=Number(q('cmPriority').value),position=Number(q('cmPosition').value);if(!id){q('cmStatus').textContent='Selecione uma categoria existente.';return}if(!Number.isInteger(position)||position<1||position>9999){q('cmStatus').textContent='Informe uma posição entre 1 e 9999.';return}q('cmStatus').textContent='Salvando tabela e posição...';try{await cfgPost({action:'set_category_placement',token,id,prioridade_acomp:priority,posicao_acomp:position});q('cmStatus').className='ok';q('cmStatus').textContent='Tabela e posição salvas. Regras e metas preservadas.';await carregarTudo();cmRenderCategoryList()}catch(e){q('cmStatus').className='bad';q('cmStatus').textContent=e.message}};
window.cmSaveCategory=async function(){const id=+q('cmId').value||null,nome=q('cmName').value.trim(),campo=q('cmField').value,modo=q('cmMode').value,ex=q('cmExclude').value.split(',').map(x=>x.trim()).filter(Boolean);if(!nome){q('cmStatus').className='bad';q('cmStatus').textContent='Informe o nome da categoria.';return}const vals=cmGroups.map(g=>g.filter(Boolean)).filter(g=>g.length);if(!vals.length){q('cmStatus').className='bad';q('cmStatus').textContent='Selecione pelo menos uma opção da planilha de vendas.';return}const op=campo==='marca'?'PREFIX_IN':campo==='descricao'?'CONTAINS':'IN';let regras=[],tipo='simples';if(modo==='ou')regras=[{grupo:1,campo,operador:op,valores:vals.flat(),obrigatorio:true,excluir_subcanais:ex}];else if(modo==='todos'){tipo='grupos';regras=vals.flat().map((v,i)=>({grupo:i+1,campo,operador:op,valores:[v],obrigatorio:true,excluir_subcanais:ex}))}else{tipo='grupos';regras=vals.map((g,i)=>({grupo:i+1,campo,operador:op,valores:g,obrigatorio:true,excluir_subcanais:ex}))}q('cmStatus').className='';q('cmStatus').textContent='Salvando...';try{const r=await cfgPost({action:'save_category_full',token,id,nome,tipo_regra:tipo,prioridade_acomp:Number(q('cmPriority').value),regras});q('cmStatus').className='ok';q('cmStatus').textContent='Categoria e regra salvas.';await carregarTudo();await cmEditCategory(r.id)}catch(e){q('cmStatus').className='bad';q('cmStatus').textContent=e.message}};
window.cmDeleteCategory=async function(){const id=+q('cmId').value;if(!id||!confirm('Excluir esta categoria, suas regras e metas?'))return;try{await cfgPost({action:'delete_category',token,id});cmNewCategory();await carregarTudo()}catch(e){q('cmStatus').className='bad';q('cmStatus').textContent=e.message}};
setTimeout(install,50)
})();