(()=>{
const API='https://harlrfhukjvhpufwhtep.supabase.co/functions/v1/imperdoaveis-api';const $=id=>document.getElementById(id);let editId=0,items=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
async function post(b){const token=sessionStorage.getItem('admToken')||'';const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...b,token})}),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'Erro');return j}
function css(){if($('impAdminStyle'))return;const s=document.createElement('style');s.id='impAdminStyle';s.textContent=`.impAdmBox{background:#fff;border-radius:18px;padding:18px}.impAdmHint{background:#fff4cf;border:1px solid #eed06b;border-radius:12px;padding:12px;margin:10px 0 16px;font-size:13px}.impAdmForm{display:grid;grid-template-columns:1fr 1fr;gap:10px}.impAdmForm input,.impAdmForm select{width:100%;padding:11px;border:1px solid #cbd5df;border-radius:10px}.impAdmWide{grid-column:1/-1}.impAdmBtns{display:flex;gap:8px;margin:12px 0}.impRule{display:grid;grid-template-columns:80px 1fr auto;gap:12px;align-items:center;padding:12px;border-top:1px solid #e2e7eb}.impCatBadge{padding:8px;border-radius:9px;background:#ffe9ea;color:#b40000;font-weight:900;text-align:center}.impRule small{display:block;color:#677786;margin-top:4px}.impRuleBtns{display:flex;gap:6px}.impRuleBtns button{padding:8px 10px}@media(max-width:700px){.impAdmForm{grid-template-columns:1fr}.impAdmWide{grid-column:1}.impRule{grid-template-columns:1fr}.impRuleBtns{justify-content:flex-start}}`;document.head.appendChild(s)}
function build(){if($('imperdoaveisAdmin'))return true;const wrap=document.querySelector('.wrap');if(!wrap)return false;const sec=document.createElement('section');sec.id='imperdoaveisAdmin';sec.className='hide';sec.innerHTML=`<div class="impAdmBox"><h2>🎯 Parâmetros Imperdoáveis</h2><div class="impAdmHint"><b>Como funciona:</b> cada linha abaixo é um produto/slot obrigatório. Se colocar vários códigos ou valores na mesma linha, qualquer um deles atende aquele slot. Use <b>*</b> em Subcanal para uma regra que vale para todos. O sistema não inventa produtos: cliente sem regra cadastrada fica como <b>Sem parâmetro</b>.</div><div class="impAdmForm"><label>Categoria<select id="impAdmCat"><option>NARTD</option><option>SSD</option><option>STILL</option><option>ARTD</option></select></label><label>Subcanal<input id="impAdmSub" value="*" placeholder="Ex.: BAR ou *"></label><label class="impAdmWide">Nome do produto / slot<input id="impAdmNome" placeholder="Ex.: CCO PT 200ml ou LT 220ml"></label><label>Buscar por<select id="impAdmCampo"><option value="material">Código do material</option><option value="marca">Marca</option><option value="descricao">Descrição</option><option value="marca_descricao">Marca + descrição</option></select></label><label>Condição<select id="impAdmOp"><option value="IN">Igual a um dos valores</option><option value="CONTAINS">Contém</option><option value="PREFIX_IN">Começa com</option></select></label><label class="impAdmWide">Códigos / valores aceitos<input id="impAdmValores" placeholder="Separe por vírgula. Ex.: 1234, 5678"></label><label>Ordem<input id="impAdmOrdem" type="number" value="1000"></label></div><div class="impAdmBtns"><button class="red" id="impAdmSave">SALVAR REGRA</button><button id="impAdmNew">NOVA</button></div><p id="impAdmStatus"></p><div id="impAdmList"></div></div>`;wrap.appendChild(sec);$('impAdmSave').onclick=save;$('impAdmNew').onclick=reset;return true}
function addCard(){const grid=document.querySelector('#cokeHome .menuGrid');if(!grid||$('impAdminCard'))return;const b=document.createElement('button');b.id='impAdminCard';b.className='menuCard';b.innerHTML='<span class="mi" style="background:#c90b13">🎯</span><span><b>Parâmetros Imperdoáveis</b><small>Configurar subcanais, produtos e oportunidades</small></span>';b.onclick=open;grid.appendChild(b)}
function showOnly(){document.querySelectorAll('.wrap>section').forEach(e=>e.classList.add('hide'));$('imperdoaveisAdmin').classList.remove('hide');$('backHome')?.remove();const wrap=document.querySelector('.wrap'),b=document.createElement('button');b.id='backHome';b.className='backHome';b.textContent='← Voltar ao menu administrativo';b.onclick=()=>{$('imperdoaveisAdmin').classList.add('hide');$('cokeHome')?.classList.remove('hide');b.remove()};wrap.insertBefore(b,wrap.firstChild)}
async function open(){if(!build())return;showOnly();reset();await load()}
async function load(){try{const j=await post({action:'list_rules'});items=j.items||[];render()}catch(e){$('impAdmList').innerHTML='<div>'+esc(e.message)+'</div>'}}
function render(){$('impAdmList').innerHTML=items.length?items.map(x=>`<div class="impRule"><div class="impCatBadge">${esc(x.categoria)}</div><div><b>${esc(x.nome_slot)}</b><small>Subcanal: ${esc(x.subcanal)} • ${esc(x.campo)} / ${esc(x.operador)}</small><small>Valores: ${esc((x.valores||[]).join(', '))}</small></div><div class="impRuleBtns"><button onclick="window.editImpRule(${x.id})">EDITAR</button><button class="red" onclick="window.delImpRule(${x.id})">EXCLUIR</button></div></div>`).join(''):'<div style="padding:16px;color:#657482">Nenhum parâmetro cadastrado ainda.</div>'}
function reset(){editId=0;if($('impAdmCat'))$('impAdmCat').value='NARTD';if($('impAdmSub'))$('impAdmSub').value='*';if($('impAdmNome'))$('impAdmNome').value='';if($('impAdmCampo'))$('impAdmCampo').value='material';if($('impAdmOp'))$('impAdmOp').value='IN';if($('impAdmValores'))$('impAdmValores').value='';if($('impAdmOrdem'))$('impAdmOrdem').value='1000';if($('impAdmStatus'))$('impAdmStatus').textContent=''}
window.editImpRule=id=>{const x=items.find(v=>v.id===id);if(!x)return;editId=x.id;$('impAdmCat').value=x.categoria;$('impAdmSub').value=x.subcanal;$('impAdmNome').value=x.nome_slot;$('impAdmCampo').value=x.campo;$('impAdmOp').value=x.operador;$('impAdmValores').value=(x.valores||[]).join(', ');$('impAdmOrdem').value=x.ordem||1000;window.scrollTo({top:0,behavior:'smooth'})};
window.delImpRule=async id=>{if(!confirm('Excluir esta regra do Imperdoáveis?'))return;try{await post({action:'delete_rule',id});await load()}catch(e){alert(e.message)}};
async function save(){const vals=$('impAdmValores').value.split(',').map(x=>x.trim()).filter(Boolean);if(!$('impAdmNome').value.trim()||!vals.length)return alert('Informe o nome do slot e pelo menos um código/valor.');$('impAdmStatus').textContent='Salvando...';try{await post({action:'save_rule',item:{id:editId||undefined,categoria:$('impAdmCat').value,subcanal:$('impAdmSub').value.trim()||'*',nome_slot:$('impAdmNome').value.trim(),campo:$('impAdmCampo').value,operador:$('impAdmOp').value,valores:vals,ordem:Number($('impAdmOrdem').value||1000),ativo:true}});reset();$('impAdmStatus').textContent='Regra salva. Os consultores usarão este parâmetro automaticamente.';await load()}catch(e){$('impAdmStatus').textContent=e.message}}
function boot(){css();build();addCard();setInterval(addCard,700)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();