(()=>{
const DAYS=['DOM','SEG','TER','QUA','QUI','SEX','SAB'];let rows=[],loaded=false;
const norm=v=>String(v??'').trim().toUpperCase();const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function parse(text){const ls=text.trim().split(/\r?\n/);if(!ls.length)return[];const h=ls.shift().split(';');return ls.filter(Boolean).map(l=>{const a=l.split(';'),o={};h.forEach((k,i)=>o[k]=a[i]||'');return o})}
async function load(){if(loaded)return;const fs=[0,1,2,3,4].map(i=>`admin-app/visitas_full_part${i}.csv?v=20260910-pvdia-01`);const ps=await Promise.all(fs.map(f=>fetch(f,{cache:'no-store'}).then(r=>r.ok?r.text():Promise.reject(Error('Falha ao carregar clientes do dia')))));rows=ps.flatMap(parse);loaded=true}
function route(){return String(document.querySelector('#route')?.textContent||'').trim()}
function day(){return DAYS[new Date().getDay()]}
function searchBox(){const hs=[...document.querySelectorAll('h1,h2,h3')].filter(x=>/Pesquisar PV/i.test(x.textContent||''));for(const h of hs){const root=h.closest('.modal,.overlay,.sheet,.cvSheet,[role="dialog"]')||h.parentElement?.parentElement||h.parentElement;if(!root)continue;const input=root.querySelector('input');const btn=[...root.querySelectorAll('button')].find(b=>/Pesquisar/i.test(b.textContent||''));if(input&&btn)return{root,input,btn,h}}return null}
function css(){if(document.getElementById('pvDiaStyle'))return;const s=document.createElement('style');s.id='pvDiaStyle';s.textContent=`.pvDiaBox{margin:12px 14px 14px;background:#fff;border:1px solid #d7e0e7;border-radius:14px;padding:12px}.pvDiaHead{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-bottom:8px}.pvDiaHead b{font-size:14px}.pvDiaHead span{font-size:11px;font-weight:900;color:#b40000;background:#fff0f0;padding:5px 8px;border-radius:999px}.pvDiaSelect{width:100%;padding:11px;border:1px solid #cbd5df;border-radius:10px;background:#fff;font-size:14px}.pvDiaHint{font-size:11px;color:#5f6d79;margin-top:7px}.pvDiaEmpty{font-size:12px;color:#7a8792;padding:8px 0}@media(max-width:600px){.pvDiaBox{margin:10px 8px}.pvDiaHead{align-items:flex-start;flex-direction:column}}`;document.head.appendChild(s)}
async function inject(){css();const b=searchBox();if(!b||b.root.querySelector('.pvDiaBox'))return;await load();const d=day(),rt=route();if(!['SEG','TER','QUA','QUI','SEX'].includes(d)||!rt)return;const list=rows.filter(x=>String(x.Rota||'').trim()===rt&&Number(x[d]||0)>0).sort((a,c)=>Number(a[d]||9999)-Number(c[d]||9999)||String(a['Razão Social']||'').localeCompare(String(c['Razão Social']||''),'pt-BR'));const box=document.createElement('div');box.className='pvDiaBox';box.innerHTML=`<div class="pvDiaHead"><b>📍 Clientes de hoje</b><span>${d} • ${list.length} cliente(s)</span></div>${list.length?`<select class="pvDiaSelect"><option value="">Selecione um cliente do dia...</option>${list.map(x=>`<option value="${esc(x.Cliente)}">${esc(x[d])} • ${esc(x.Cliente)} • ${esc(x['Razão Social'])}</option>`).join('')}</select><div class="pvDiaHint">Ao escolher, o PV é pesquisado automaticamente e mostra o que falta para esse cliente.</div>`:`<div class="pvDiaEmpty">Nenhum cliente programado para hoje nesta rota.</div>`}`;const anchor=b.input.closest('form')||b.input.parentElement?.parentElement||b.input.parentElement;b.root.insertBefore(box,anchor?.nextSibling||b.root.lastChild);const sel=box.querySelector('select');if(sel)sel.onchange=()=>{if(!sel.value)return;b.input.value=sel.value;b.input.dispatchEvent(new Event('input',{bubbles:true}));setTimeout(()=>b.btn.click(),50)}}
function watch(){inject().catch(()=>{});setInterval(()=>inject().catch(()=>{}),700)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch);else watch();
})();