(()=>{
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const norm=v=>String(v??'').trim().toUpperCase();
let allRows=[],loaded=false;
const days=['SEG','TER','QUA','QUI','SEX'];
function freq(v){const n=norm(v);if(n.includes('SEMANAL'))return 'SEM';if(n.includes('QUINZENAL-PAR'))return 'Q-PAR';if(n.includes('QUINZENAL-ÍMPAR')||n.includes('QUINZENAL-IMPAR'))return 'Q-ÍMPAR';return String(v||'');}
function badge(v){const f=freq(v);return `<span style="display:inline-block;padding:3px 6px;border-radius:999px;background:#eef1f4;font-size:10px;font-weight:900">${esc(f)}</span>`}
function phone(v){const t=String(v||'').trim();if(!t)return '';const d=t.replace(/\D/g,'');return `<a href="tel:${esc(d)}" style="font-weight:900;color:#0b63ce;text-decoration:none;white-space:nowrap">☎ ${esc(t)}</a>`}
function parse(text){const lines=text.trim().split(/\r?\n/);if(!lines.length)return[];const head=lines.shift().split(';');return lines.filter(Boolean).map(l=>{const a=l.split(';'),o={};head.forEach((h,i)=>o[h]=a[i]||'');return o})}
async function loadRows(){if(loaded)return;const files=[0,1,2,3,4].map(i=>`admin-app/visitas_full_part${i}.csv?v=20260909-consultor-03`);const parts=await Promise.all(files.map(f=>fetch(f,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Falha ao carregar visitas');return r.text()})));allRows=parts.flatMap(parse);loaded=true;}
function route(){return String(document.getElementById('route')?.textContent||'').trim()}
function own(){const r=route();return allRows.filter(x=>String(x.Rota||'').trim()===r)}
function ensureCss(){if($('cvStyle'))return;const st=document.createElement('style');st.id='cvStyle';st.textContent=`.summary{display:none!important}.quick{grid-template-columns:repeat(6,minmax(0,1fr))!important}.quick .cvTopBtn{grid-column:span 2;order:1}.quick .cvBottomBtn{grid-column:span 3;order:2}.cvBtn{border:0;border-radius:16px;padding:16px;text-align:left;font-weight:900;background:#fff;border:1px solid #d9e0e6}.cvBtn.red{background:#e30613;color:#fff;border:0}.cvOverlay{display:none;position:fixed;inset:0;background:#0009;z-index:40;padding:12px}.cvOverlay.show{display:flex;align-items:center;justify-content:center}.cvSheet{background:#f4f6f8;width:min(1100px,100%);max-height:94vh;overflow:auto;border-radius:20px}.cvTop{position:sticky;top:0;background:linear-gradient(135deg,#090909,#9f0000);color:#fff;padding:15px;display:flex;justify-content:space-between;align-items:center;z-index:2}.cvTop button{border:0;border-radius:9px;padding:9px 12px}.cvBody{padding:12px}.cvFilters{display:grid;grid-template-columns:170px 1fr;gap:8px}.cvFilters select,.cvFilters input{padding:10px;border:1px solid #ccd5dd;border-radius:10px;width:100%}.cvCards{display:grid;grid-template-columns:repeat(auto-fit,minmax(185px,1fr));gap:8px;margin-top:10px}.cvCard{border:1px solid #dfe5ea;background:#fff;border-radius:12px;padding:11px;text-align:left;cursor:pointer}.cvCard b{display:block}.cvCard strong{font-size:22px;color:#d40000}.cvNotice{background:#fff3df;border-radius:10px;padding:10px;margin-top:9px;font-weight:900}.cvTable table{font-size:12px!important;min-width:980px!important}.cvTable th,.cvTable td{padding:7px 8px!important;line-height:1.15!important;vertical-align:middle!important}.cvTable td:nth-child(4){max-width:220px;white-space:normal}@media(max-width:700px){.cvFilters{grid-template-columns:1fr}.quick{grid-template-columns:repeat(6,minmax(0,1fr))!important}.quick .cvTopBtn{grid-column:span 2}.quick .cvBottomBtn{grid-column:span 3}.quick button{font-size:12px;padding:12px 8px}.cvTable table{font-size:11px!important}}`;document.head.appendChild(st)}
function ensureOverlays(){if(!$('cvVisits')){document.body.insertAdjacentHTML('beforeend',`<div id="cvVisits" class="cvOverlay"><div class="cvSheet"><div class="cvTop"><h2>📍 Minhas Visitas</h2><button onclick="window.cvClose('cvVisits')">Fechar</button></div><div class="cvBody"><div class="cvFilters"><select id="cvDay"><option value="ALL">Todos os dias</option><option>SEG</option><option>TER</option><option>QUA</option><option>QUI</option><option>SEX</option></select><input id="cvSearch" placeholder="Pesquisar PV, razão, subcanal, cidade..."></div><div id="cvVisitSummary" class="cvNotice"></div><div class="tableWrap cvTable"><table><thead><tr><th>Ordem</th><th>Dia</th><th>PV</th><th>Razão Social</th><th>Subcanal</th><th>Freq.</th><th>Cidade</th><th>Telefone</th></tr></thead><tbody id="cvVisitTb"></tbody></table></div></div></div></div>`);$('cvDay').onchange=renderVisits;$('cvSearch').oninput=renderVisits}
if(!$('cvSubs')){document.body.insertAdjacentHTML('beforeend',`<div id="cvSubs" class="cvOverlay"><div class="cvSheet"><div class="cvTop"><h2>🏪 Meus Subcanais</h2><button onclick="window.cvClose('cvSubs')">Fechar</button></div><div class="cvBody"><div class="cvFilters"><div class="cvNotice" style="margin:0" id="cvSubTotal"></div><input id="cvSubSearch" placeholder="Pesquisar subcanal..."></div><div id="cvCards" class="cvCards"></div><h3 id="cvSubTitle">Clientes</h3><div class="tableWrap cvTable"><table><thead><tr><th>PV</th><th>Razão Social</th><th>Subcanal</th><th>Freq.</th><th>SEG</th><th>TER</th><th>QUA</th><th>QUI</th><th>SEX</th><th>Cidade</th><th>Telefone</th></tr></thead><tbody id="cvSubTb"></tbody></table></div></div></div></div>`);$('cvSubSearch').oninput=renderSubs}}
window.cvClose=id=>$(id)?.classList.remove('show');
async function openVisits(){await loadRows();ensureOverlays();renderVisits();$('cvVisits').classList.add('show')}
async function openSubs(){await loadRows();ensureOverlays();renderSubs();$('cvSubs').classList.add('show')}
function renderVisits(){if(!$('cvVisitTb'))return;const d=$('cvDay').value,s=norm($('cvSearch').value);let rows=own().filter(x=>(d==='ALL'||Number(x[d]||0)>0)&&(!s||norm([x.Cliente,x['Razão Social'],x.SubCanal,x.Cidade,x.Telefone].join(' ')).includes(s)));$('cvVisitSummary').textContent=`${rows.length} cliente(s) • Rota ${route()}`;let out=[];rows.forEach(x=>{let ds=days.filter(day=>Number(x[day]||0)>0);if(d!=='ALL')ds=ds.filter(day=>day===d);ds.forEach(day=>out.push({...x,_dia:day,_ord:Number(x[day]||0)}))});out.sort((a,b)=>days.indexOf(a._dia)-days.indexOf(b._dia)||(a._ord||9999)-(b._ord||9999));$('cvVisitTb').innerHTML=out.length?out.map(x=>`<tr><td>${x._ord||''}</td><td><b>${esc(x._dia)}</b></td><td><b>${esc(x.Cliente)}</b></td><td>${esc(x['Razão Social'])}</td><td>${esc(x.SubCanal)}</td><td>${badge(x['Freq visita'])}</td><td>${esc(x.Cidade)}</td><td>${phone(x.Telefone)}</td></tr>`).join(''):'<tr><td colspan="8" class="empty">Nenhum cliente encontrado.</td></tr>'}
function renderSubs(){if(!$('cvCards'))return;const base=own(),s=norm($('cvSubSearch').value),counts={};base.forEach(x=>{const k=(x.SubCanal||'SEM SUBCANAL').trim();counts[k]=(counts[k]||0)+1});const keys=Object.keys(counts).filter(k=>!s||norm(k).includes(s)).sort((a,b)=>counts[b]-counts[a]||a.localeCompare(b,'pt-BR'));$('cvSubTotal').innerHTML=`<b>${base.length} clientes</b> • Rota ${esc(route())}`;$('cvCards').innerHTML=keys.map(k=>`<button class="cvCard" data-sub="${esc(k)}"><b>${esc(k)}</b><strong>${counts[k]}</strong><small> cliente(s) • clique para listar</small></button>`).join('');document.querySelectorAll('#cvCards .cvCard').forEach(b=>b.onclick=()=>showSub(b.dataset.sub));showSub('ALL')}
function showSub(k){const base=own();let rows=k==='ALL'?base:base.filter(x=>(x.SubCanal||'SEM SUBCANAL').trim()===k);$('cvSubTitle').textContent=k==='ALL'?`Clientes • Todos (${rows.length})`:`Clientes • ${k} (${rows.length})`;rows.sort((a,b)=>String(a['Razão Social']).localeCompare(String(b['Razão Social']),'pt-BR'));$('cvSubTb').innerHTML=rows.length?rows.map(x=>`<tr><td><b>${esc(x.Cliente)}</b></td><td>${esc(x['Razão Social'])}</td><td>${esc(x.SubCanal)}</td><td>${badge(x['Freq visita'])}</td><td>${esc(x.SEG||'')}</td><td>${esc(x.TER||'')}</td><td>${esc(x.QUA||'')}</td><td>${esc(x.QUI||'')}</td><td>${esc(x.SEX||'')}</td><td>${esc(x.Cidade)}</td><td>${phone(x.Telefone)}</td></tr>`).join(''):'<tr><td colspan="11" class="empty">Nenhum cliente encontrado.</td></tr>'}
function install(){ensureCss();const q=document.querySelector('.quick');if(!q){setTimeout(install,150);return}const pv=q.querySelector('.pv'),trio=q.querySelector('.trio'),hei=q.querySelector('.hei');if(pv)pv.classList.add('cvTopBtn');if(trio)trio.classList.add('cvBottomBtn');if(hei)hei.classList.add('cvBottomBtn');if(!$('cvVisitBtn')){const b=document.createElement('button');b.id='cvVisitBtn';b.className='cvBtn red cvTopBtn';b.innerHTML='📍 Visita de Clientes<br><small>Veja seus dias e sequência</small>';b.onclick=openVisits;q.appendChild(b)}if(!$('cvSubBtn')){const b=document.createElement('button');b.id='cvSubBtn';b.className='cvBtn cvTopBtn';b.innerHTML='🏪 Subcanais<br><small>Veja seus clientes por perfil</small>';b.onclick=openSubs;q.appendChild(b)}ensureOverlays()}
function waitForRoute(){if(route()){install();return}setTimeout(waitForRoute,250)}
install();waitForRoute();
})();